repos:
  -
    hooks:
      -
        id: black
    repo: "https://github.com/psf/black"
    rev: 23.1.0
  -
    hooks:
      -
        id: poetry-check
      -
        id: poetry-lock
      -
        id: poetry-export
    repo: "https://github.com/python-poetry/poetry"
    rev: 1.3.0
